version: "3.8"

services:
  ros2_galactic:
    build: .
    container_name: ros2_galactic

    network_mode: host   # --net=host

    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - DISPLAY=${DISPLAY}       # ★ 追加

    stdin_open: true     # -i
    tty: true            # -t

    restart: "no"        # --rm 相当

    volumes:
      #      - /dev:/dev   # 必要ならセンサ等用（AGV用途で推奨）
      - /tmp/.X11-unix:/tmp/.X11-unix  # ★ 追加

